version: '3.8'

services:
  mongo:
    image: mongo:7
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

  backend:
    image: kikitha/mean-backend:latest
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/mean-crud
    ports:
      - 3000:8080
    depends_on:
      - mongo

  frontend:
    image: kikitha/mean-frontend:latest
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  mongo-data:
